version: "3.9"
services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1.21-bullseye
    container_name: app
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "8080:8080"
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"



