name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    env:
      COVERPROFILE: ./profile.cov
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: [1.21.x, 1.22.x]
        # Run coverage only on Ubuntu with Go 1.22.x
        include:
          - os: ubuntu-latest
            go-version: 1.22.x
            coverage: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        shell: bash
        run: make build

      - name: Run Tests
        shell: bash
        run: make test

      - name: Run Coverage
        if: ${{ matrix.coverage }}
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ${{ env.COVERPROFILE }}

  release:
    name: Release
    needs: [test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions: 
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: Run Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}